# Generated by Django 4.0.3 on 2022-03-13 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_budget_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='due_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
